language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
  - 1.12
  - tip
env:
  - GOARCH=386
  - GOARCH=amd64
matrix:
  allow_failures:
    - go: tip
install:
  - go get github.com/smartystreets/goconvey
  - go get github.com/pborman/uuid
  - go get github.com/go-errors/errors